---
- name: Sensitive Data
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Report secret
      ansible.builtin.debug:
        msg: "My secret is: {{ my_secret }}"
        verbosity: 2
